name: Build Lambda Layer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      lambda-layer-builder:
        image: amazonlinux:2
        options: --entrypoint /bin/sh

    strategy:
      matrix:
        python-version: [3.8, 3.9]  # Add more Python versions as needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t .

      - name: Package Lambda layer
        run: zip -r python${{ matrix.python-version }}-requests-layer.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: python${{ matrix.python-version }}-requests-layer
          path: python${{ matrix.python-version }}-requests-layer.zip
